## This is the configuration file for Netlify
## https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run build" # how to build your project
  publish = ".output/public" # where the built project lives

[build.environment]
  NODE_VERSION = "18"